"""<descriptive message>

Revision ID: 2ecd46cbf048
Revises: 
Create Date: 2023-08-09 15:52:05.161666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecd46cbf048'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shitty_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_name', sa.String(), nullable=True),
    sa.Column('idea_description', sa.String(), nullable=True),
    sa.Column('shittiness_scale', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_3_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('fun_scale', sa.Integer(), nullable=True),
    sa.Column('shitty_idea_id', sa.Integer(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_phase_3_projects_developer_id_developers')),
    sa.ForeignKeyConstraint(['shitty_idea_id'], ['shitty_ideas.id'], name=op.f('fk_phase_3_projects_shitty_idea_id_shitty_ideas')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase_3_projects')
    op.drop_table('shitty_ideas')
    op.drop_table('developers')
    # ### end Alembic commands ###
