"""<descriptive message>

Revision ID: acbaaa6e4f6a
Revises: e5c1ff19a0f6
Create Date: 2023-08-10 15:55:03.630853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbaaa6e4f6a'
down_revision: Union[str, None] = 'e5c1ff19a0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
